In [1]:
import pandas as pd
import numpy as np
import csv
import os
import sqlite3
import sqlalchemy
from sqlalchemy import create_engine

In [2]:
review_file = "google-play-store-apps/googleplaystore_user_reviews.csv"
review_df = pd.read_csv(review_file)
review_df.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [3]:
app_file = "google-play-store-apps/googleplaystore.csv"
app_df = pd.read_csv(app_file)
app_df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [4]:
merge_df = pd.merge(app_df, review_df, on="App")
merge_df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,A kid's excessive ads. The types ads allowed a...,Negative,-0.250,1.000000
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,It bad >:(,Negative,-0.725,0.833333
2,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,like,Neutral,0.000,0.000000
3,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,NaN,NaN,NaN,NaN
4,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,I love colors inspyering,Positive,0.500,0.600000

In [5]:
drop_columns = ["Size",'Content Rating','Genres','Last Updated', 'Sentiment_Polarity','Sentiment_Subjectivity']
clean_df = merge_df.drop(drop_columns, axis=1)
clean_df.head()

,App,Category,Rating,Reviews,Installs,Type,Price,Current Ver,Android Ver,Translated_Review,Sentiment
0,Coloring book moana,ART_AND_DESIGN,3.9,967,"500,000+",Free,0,2.0.0,4.0.3 and up,A kid's excessive ads. The types ads allowed a...,Negative
1,Coloring book moana,ART_AND_DESIGN,3.9,967,"500,000+",Free,0,2.0.0,4.0.3 and up,It bad >:(,Negative
2,Coloring book moana,ART_AND_DESIGN,3.9,967,"500,000+",Free,0,2.0.0,4.0.3 and up,like,Neutral
3,Coloring book moana,ART_AND_DESIGN,3.9,967,"500,000+",Free,0,2.0.0,4.0.3 and up,NaN,NaN
4,Coloring book moana,ART_AND_DESIGN,3.9,967,"500,000+",Free,0,2.0.0,4.0.3 and up,I love colors inspyering,Positive

In [6]:
clean_df = clean_df.dropna()
clean_df.count()

App                  72566
Category             72566
Rating               72566
Reviews              72566
Installs             72566
Type                 72566
Price                72566
Current Ver          72566
Android Ver          72566
Translated_Review    72566
Sentiment            72566
dtype: int64

In [7]:
conn = sqlite3.connect("googleapps.sqlite")

In [8]:
final_db = clean_df.to_sql("apps", conn)

C:\Users\jnovic\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\generic.py:2127: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  dtype=dtype)

ValueError: Table 'apps' already exists.

In [9]:
engine = create_engine("sqlite:///googleapps.sqlite")

In [12]:
data = engine.execute("SELECT * FROM apps LIMIT 5")

In [13]:
for record in data:
    print(record)

(0, 'Coloring book moana', 'ART_AND_DESIGN', 3.9, '967', '500,000+', 'Free', '0', '2.0.0', '4.0.3 and up', "A kid's excessive ads. The types ads allowed app, let alone kids", 'Negative')
(1, 'Coloring book moana', 'ART_AND_DESIGN', 3.9, '967', '500,000+', 'Free', '0', '2.0.0', '4.0.3 and up', 'It bad >:(', 'Negative')
(2, 'Coloring book moana', 'ART_AND_DESIGN', 3.9, '967', '500,000+', 'Free', '0', '2.0.0', '4.0.3 and up', 'like', 'Neutral')
(4, 'Coloring book moana', 'ART_AND_DESIGN', 3.9, '967', '500,000+', 'Free', '0', '2.0.0', '4.0.3 and up', 'I love colors inspyering', 'Positive')
(5, 'Coloring book moana', 'ART_AND_DESIGN', 3.9, '967', '500,000+', 'Free', '0', '2.0.0', '4.0.3 and up', 'I hate', 'Negative')